# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_grading',
            name='klasifikasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
