# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 03:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id_pemasok', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('nama_pemasok', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_bb', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'dim_pemasok',
            },
        ),
    ]
